apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: vxmm/my-repo:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: docker-hub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000