apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 975050137696.dkr.ecr.us-east-1.amazonaws.com/vxmm/my-repo:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32152
  type: NodePort