name: Deploy to CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-CloudFormation

      - name: Upload code to S3
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
      - name: Upload code to S3 bucket
        run: |
          aws s3 cp --recursive --profile default code/ s3://${{ secrets.S3_BUCKET_NAME }}

      - name: Update CloudFormation stack
        run: |
          aws cloudformation update-stack --stack-name my-stack --template-body-file my-template.yaml
